require "./vcs/git"

module Carbon
  class HookManager
    START_DELIMITER = "# >>> CARBON AUTO-VERSION HOOK >>>"
    END_DELIMITER   = "# <<< CARBON AUTO-VERSION HOOK <<<"

    HOOK_BODY = <<-HOOK
    #{START_DELIMITER}
    # Generated by Carbon. Do not edit this block manually.
    if [ -f "bin/carbon" ]; then
      ./bin/carbon bump --hook
    elif [ -f "bin/carbon.exe" ]; then
      ./bin/carbon.exe bump --hook
    elif command -v carbon >/dev/null 2>&1; then
      carbon bump --hook
    elif command -v crystal >/dev/null 2>&1; then
      if [ -f "src/carbon/cli.cr" ]; then
        crystal run src/carbon/cli.cr -- bump --hook
      elif [ -f "lib/carbon/src/carbon/cli.cr" ]; then
        crystal run lib/carbon/src/carbon/cli.cr -- bump --hook
      fi
    fi
    #{END_DELIMITER}
    HOOK

    POST_MERGE_HOOK_BODY = <<-HOOK
    #{START_DELIMITER}
    # Generated by Carbon. Do not edit this block manually.
    if [ -f "bin/carbon" ]; then
      ./bin/carbon sync
    elif [ -f "bin/carbon.exe" ]; then
      ./bin/carbon.exe sync
    elif command -v carbon >/dev/null 2>&1; then
      carbon sync
    elif command -v crystal >/dev/null 2>&1; then
      if [ -f "src/carbon/cli.cr" ]; then
        crystal run src/carbon/cli.cr -- sync
      elif [ -f "lib/carbon/src/carbon/cli.cr" ]; then
        crystal run lib/carbon/src/carbon/cli.cr -- sync
      fi
    fi
    #{END_DELIMITER}
    HOOK

    def self.hook_body(hook_name : String = "pre-commit") : String
      hook_name == "post-merge" ? POST_MERGE_HOOK_BODY : HOOK_BODY
    end

    def self.hook_path(repo_root : Path | String = ".", hook_name : String = "pre-commit") : Path
      git = VCS::Git.new(repo_root)
      git.vcs_dir.join("hooks", hook_name)
    end

    def self.installed?(repo_root : Path | String = ".", hook_name : String = "pre-commit") : Bool
      path = hook_path(repo_root, hook_name)
      return false unless File.exists?(path)
      File.read(path).includes?(START_DELIMITER)
    end

    def self.install(repo_root : Path | String = ".", hook_name : String = "pre-commit") : Bool
      path = hook_path(repo_root, hook_name)
      parent = path.parent
      Dir.mkdir_p(parent) unless Dir.exists?(parent)

      hook_content = hook_body(hook_name).strip

      if File.exists?(path)
        existing = File.read(path)
        if existing.includes?(START_DELIMITER) && existing.includes?(END_DELIMITER)
          # Replace existing block
          regex = /#{Regex.escape(START_DELIMITER)}[\s\S]*?#{Regex.escape(END_DELIMITER)}/
          new_content = existing.gsub(regex, hook_content)
          File.write(path, new_content)
        else
          # Append to existing hook
          separator = existing.ends_with?("\n") ? "" : "\n"
          File.write(path, existing + separator + "\n" + hook_content + "\n")
        end
      else
        # Create fresh hook script
        script = "#!/bin/sh\n\n" + hook_content + "\n"
        File.write(path, script)
      end

      # Attempt to make executable on POSIX systems
      begin
        File.chmod(path, 0o755)
      rescue
        # Ignored on platforms without posix permissions support
      end

      true
    end

    def self.uninstall(repo_root : Path | String = ".", hook_name : String = "pre-commit") : Bool
      path = hook_path(repo_root, hook_name)
      return false unless File.exists?(path)

      existing = File.read(path)
      return false unless existing.includes?(START_DELIMITER)

      regex = /#{Regex.escape(START_DELIMITER)}[\s\S]*?#{Regex.escape(END_DELIMITER)}/
      updated = existing.gsub(regex, "").strip

      if updated.empty? || updated == "#!/bin/sh"
        File.delete(path)
      else
        File.write(path, updated + "\n")
      end

      true
    end
  end
end
